kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: spring-maven-example-0-2
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'spring-maven-example:0.2'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'java:latest'
  source:
    type: Git
    git:
      uri: 'https://github.com/smatz-ITGAIN/spring-maven-example.git'
